djangoLevelFour/basicapp2/urls.py
from django.urls import path
from basicapp2 import views

#TEMPLATE TAGGING
app_name = 'basicapp2'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

djangoLevelFour/djangoLevelFour/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basicapp2 import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basicapp2/', include('basicapp2.urls')),
    path('admin/', admin.site.urls),
]

djangoLevelFour/basicapp2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request, 'basicapp2/index.html', context_dict)

def other(request):
    return render(request, 'basicapp2/other.html')

def relative(request):
    return render(request, 'basicapp2/relative_url_templates.html')

djangoLevelFour/templates/basicapp2/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basicapp2:other'%}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>
</body>
</html>

djangoLevelFour/templates/basicapp2/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
{% extends "basicapp2/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO INDEX!</h1>
        <h1>{{ text|cut:'world' }}</h1>
        <h1>{{ number|add:"150" }}</h1>
    {% endblock %}

djangoLevelFour/templates/basicapp2/other.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
{% extends "basicapp2/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO OTHER!</h1>
        <h2>This is the other page</h2>
    {% endblock %}

djangoLevelFour/templates/basicapp2/relative_url_templates.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title></title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>

    <a href="{% url 'basicapp2:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
</body>
</html>